#!/bin/bash

/usr/bin/hadoop fs -getmerge 25th-nujf.out 25th-nujf.out
/usr/bin/hadoop fs -getmerge 2ei9-vg68.out 2ei9-vg68.out
/usr/bin/hadoop fs -getmerge 2v9c-2k7f.out 2v9c-2k7f.out
/usr/bin/hadoop fs -getmerge 32y8-s55c.out 32y8-s55c.out
/usr/bin/hadoop fs -getmerge 35sw-rdxj.out 35sw-rdxj.out
/usr/bin/hadoop fs -getmerge 3h2n-5cm9.out 3h2n-5cm9.out
/usr/bin/hadoop fs -getmerge 43nn-pn8j.out 43nn-pn8j.out
/usr/bin/hadoop fs -getmerge 4e2n-s75z.out 4e2n-s75z.out
/usr/bin/hadoop fs -getmerge 5tub-eh45.out 5tub-eh45.out
/usr/bin/hadoop fs -getmerge 5uac-w243.out 5uac-w243.out
/usr/bin/hadoop fs -getmerge 5ucz-vwe8.out 5ucz-vwe8.out
/usr/bin/hadoop fs -getmerge 6bgk-3dad.out 6bgk-3dad.out
/usr/bin/hadoop fs -getmerge 6z8x-wfk4.out 6z8x-wfk4.out
/usr/bin/hadoop fs -getmerge 7479-ugqb.out 7479-ugqb.out
/usr/bin/hadoop fs -getmerge 76xm-jjuj.out 76xm-jjuj.out
/usr/bin/hadoop fs -getmerge 7z8d-msnt.out 7z8d-msnt.out
/usr/bin/hadoop fs -getmerge 833y-fsy8.out 833y-fsy8.out
/usr/bin/hadoop fs -getmerge 8586-3zfm.out 8586-3zfm.out
/usr/bin/hadoop fs -getmerge 867j-5pgi.out 867j-5pgi.out
/usr/bin/hadoop fs -getmerge 8h9b-rp9u.out 8h9b-rp9u.out
/usr/bin/hadoop fs -getmerge 8m42-w767.out 8m42-w767.out
/usr/bin/hadoop fs -getmerge 8wbx-tsch.out 8wbx-tsch.out
/usr/bin/hadoop fs -getmerge 9rz4-mjek.out 9rz4-mjek.out
/usr/bin/hadoop fs -getmerge a9md-ynri.out a9md-ynri.out
/usr/bin/hadoop fs -getmerge biws-g3hs.out biws-g3hs.out
/usr/bin/hadoop fs -getmerge bs8b-p36w.out bs8b-p36w.out
/usr/bin/hadoop fs -getmerge c3uy-2p5r.out c3uy-2p5r.out
/usr/bin/hadoop fs -getmerge cete-9g3v.out cete-9g3v.out
/usr/bin/hadoop fs -getmerge ci93-uc8s.out ci93-uc8s.out
/usr/bin/hadoop fs -getmerge dg92-zbpx.out dg92-zbpx.out
/usr/bin/hadoop fs -getmerge dpec-ucu7.out dpec-ucu7.out
/usr/bin/hadoop fs -getmerge dsg6-ifza.out dsg6-ifza.out
/usr/bin/hadoop fs -getmerge e98g-f8hy.out e98g-f8hy.out
/usr/bin/hadoop fs -getmerge eabe-havv.out eabe-havv.out
/usr/bin/hadoop fs -getmerge ebb7-mvp5.out ebb7-mvp5.out
/usr/bin/hadoop fs -getmerge eccv-9dzr.out eccv-9dzr.out
/usr/bin/hadoop fs -getmerge erm2-nwe9.out erm2-nwe9.out
/usr/bin/hadoop fs -getmerge evjd-dqpz.out evjd-dqpz.out
/usr/bin/hadoop fs -getmerge f7b6-v6v3.out f7b6-v6v3.out
/usr/bin/hadoop fs -getmerge f9bf-2cp4.out f9bf-2cp4.out
/usr/bin/hadoop fs -getmerge h9gi-nx95.out h9gi-nx95.out
/usr/bin/hadoop fs -getmerge hc8x-tcnd.out hc8x-tcnd.out
/usr/bin/hadoop fs -getmerge hg8x-zxpr.out hg8x-zxpr.out
/usr/bin/hadoop fs -getmerge hvrh-b6nb.out hvrh-b6nb.out
/usr/bin/hadoop fs -getmerge ia2d-e54m.out ia2d-e54m.out
/usr/bin/hadoop fs -getmerge ic3t-wcy2.out ic3t-wcy2.out
/usr/bin/hadoop fs -getmerge ipu4-2q9a.out ipu4-2q9a.out
/usr/bin/hadoop fs -getmerge jb3k-j3gp.out jb3k-j3gp.out
/usr/bin/hadoop fs -getmerge jb7j-dtam.out jb7j-dtam.out
/usr/bin/hadoop fs -getmerge jgtb-hmpg.out jgtb-hmpg.out
/usr/bin/hadoop fs -getmerge jt7v-77mi.out jt7v-77mi.out
/usr/bin/hadoop fs -getmerge jz4z-kudi.out jz4z-kudi.out
/usr/bin/hadoop fs -getmerge k397-673e.out k397-673e.out
/usr/bin/hadoop fs -getmerge k46n-sa2m.out k46n-sa2m.out
/usr/bin/hadoop fs -getmerge kf2b-aeh5.out kf2b-aeh5.out
/usr/bin/hadoop fs -getmerge kh3d-xhq7.out kh3d-xhq7.out
/usr/bin/hadoop fs -getmerge kiv2-tbus.out kiv2-tbus.out
/usr/bin/hadoop fs -getmerge kku6-nxdu.out kku6-nxdu.out
/usr/bin/hadoop fs -getmerge kpav-sd4t.out kpav-sd4t.out
/usr/bin/hadoop fs -getmerge mdcw-n682.out mdcw-n682.out
/usr/bin/hadoop fs -getmerge mifw-tguq.out mifw-tguq.out
/usr/bin/hadoop fs -getmerge muvi-b6kx.out muvi-b6kx.out
/usr/bin/hadoop fs -getmerge mwzb-yiwb.out mwzb-yiwb.out
/usr/bin/hadoop fs -getmerge n5mv-nfpy.out n5mv-nfpy.out
/usr/bin/hadoop fs -getmerge nc67-uf89.out nc67-uf89.out
/usr/bin/hadoop fs -getmerge ncbg-6agr.out ncbg-6agr.out
/usr/bin/hadoop fs -getmerge ntcm-2w4k.out ntcm-2w4k.out
/usr/bin/hadoop fs -getmerge nzjr-3966.out nzjr-3966.out
/usr/bin/hadoop fs -getmerge p424-amsu.out p424-amsu.out
/usr/bin/hadoop fs -getmerge pasr-j7fb.out pasr-j7fb.out
/usr/bin/hadoop fs -getmerge pe54-wf39.out pe54-wf39.out
/usr/bin/hadoop fs -getmerge pvqr-7yc4.out pvqr-7yc4.out
/usr/bin/hadoop fs -getmerge qgea-i56i.out qgea-i56i.out
/usr/bin/hadoop fs -getmerge rbx6-tga4.out rbx6-tga4.out
/usr/bin/hadoop fs -getmerge rc75-m7u3.out rc75-m7u3.out
/usr/bin/hadoop fs -getmerge rhe8-mgbb.out rhe8-mgbb.out
/usr/bin/hadoop fs -getmerge s52a-8aq6.out s52a-8aq6.out
/usr/bin/hadoop fs -getmerge swpk-hqdp.out swpk-hqdp.out
/usr/bin/hadoop fs -getmerge sxx4-xhzg.out sxx4-xhzg.out
/usr/bin/hadoop fs -getmerge t29m-gskq.out t29m-gskq.out
/usr/bin/hadoop fs -getmerge tesw-yqqr.out tesw-yqqr.out
/usr/bin/hadoop fs -getmerge tg4x-b46p.out tg4x-b46p.out
/usr/bin/hadoop fs -getmerge uiay-nctu.out uiay-nctu.out
/usr/bin/hadoop fs -getmerge uip8-fykc.out uip8-fykc.out
/usr/bin/hadoop fs -getmerge uq7m-95z8.out uq7m-95z8.out
/usr/bin/hadoop fs -getmerge uvpi-gqnh.out uvpi-gqnh.out
/usr/bin/hadoop fs -getmerge vfnx-vebw.out vfnx-vebw.out
/usr/bin/hadoop fs -getmerge vw9i-7mzq.out vw9i-7mzq.out
/usr/bin/hadoop fs -getmerge vx8i-nprf.out vx8i-nprf.out
/usr/bin/hadoop fs -getmerge w7w3-xahh.out w7w3-xahh.out
/usr/bin/hadoop fs -getmerge w9ak-ipjd.out w9ak-ipjd.out
/usr/bin/hadoop fs -getmerge wvxf-dwi5.out wvxf-dwi5.out
/usr/bin/hadoop fs -getmerge xi7c-iiu2.out xi7c-iiu2.out
/usr/bin/hadoop fs -getmerge xjfq-wh2d.out xjfq-wh2d.out
/usr/bin/hadoop fs -getmerge xywu-7bv9.out xywu-7bv9.out
/usr/bin/hadoop fs -getmerge y7az-s7wc.out y7az-s7wc.out
/usr/bin/hadoop fs -getmerge ye3c-m4ga.out ye3c-m4ga.out
/usr/bin/hadoop fs -getmerge yhuu-4pt3.out yhuu-4pt3.out
/usr/bin/hadoop fs -getmerge zkky-n5j3.out zkky-n5j3.out
/usr/bin/hadoop fs -getmerge zt9s-n5aj.out zt9s-n5aj.out